# environment.yml

name: classyfire_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Specify your preferred Python version
  - pip
  - rdkit>=2024.3.5
  - requests>=2.32.3
  - click>=8.1.7
  - tqdm>=4.66.5
  - pip:
      - setuptools
      - wheel
      - nose
      - coverage
