name: pyclassyfire_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - rdkit>=2024.3.5
  - requests>=2.32.3
  - click>=8.1.7
  - tqdm>=4.66.5
  - pandas>=2.2.3
  - ipykernel>=6.29
  - pip:
      - setuptools
      - wheel
      - nose
      - coverage